export const WEATHER_SEARCH_BY_CITY_INIT = '[WEATHER] WEATHER_SEARCH_BY_CITY_INIT';
export const WEATHER_SEARCH_BY_CITY_SUCCESS = '[WEATHER] WEATHER_SEARCH_BY_CITY_SUCCESS';
export const WEATHER_SEARCH_BY_CITY_ERROR = '[WEATHER] WEATHER_SEARCH_BY_CITY_ERROR';
